version: '3.1'

services:
  api:
    build: .
    depends_on:
      - db
    expose:
      - 5000
    volumes:
      - ./api:/api

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    expose:
      - 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
